sudo: required
#hey travis we will need sudo permission access to run
services:
  -docker #travis will install copy of docker

before_install:
  - docker build -t dmaniar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dmaniar/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-885826792816"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY